---


- hosts: etcd
  vars:
    etcd_version: "v3.0.4"
    etcd_release: "etcd-{{ etcd_version }}-linux-amd64"
    etcd_download_filename: "{{ etcd_release }}.tar.gz"
    etcd_download_url: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/{{ etcd_download_filename }}"
    etcd_download_dir: /usr/local/src

  tasks:
  - name: Download etcd
    get_url: url="{{ etcd_download_url }}"
             dest="{{ etcd_download_dir }}"
             # TODO Add hash check
    become: true

  - name: Unpack etcd
    unarchive: copy=no
               src="{{ etcd_download_dir }}/{{ etcd_download_filename }}"
               dest="{{ etcd_download_dir }}"
               creates="{{ etcd_download_dir }}/{{ etcd_release }}/etcd"
    become: true

  - name: Copy etcd binaries
    copy:
      remote_src: true
      src: "{{ etcd_download_dir }}/{{ etcd_release }}/{{ item }}"
      dest: "/usr/bin"
      owner: root
      group: root
      mode: 0755
    with_items:
      - etcd
      - etcdctl
    become: true

  - name: Create etcd data dir
    file: path=/var/lib/etcd state=directory
    become: true

  - name: Add etcd systemd unit
    template:
      src: etcd.service.j2
      dest: /etc/systemd/system/etcd.service
      mode: 700
    become: true

  - name: Reload systemd
    command: systemctl daemon-reload
    become: true

  - name: Enable etcd service
    command: systemctl enable etcd
    become: true

  - name: Restart etcd
    service:
      name: etcd
      state: restarted
      enabled: yes
    become: true

  - name: Wait for etcd listening
    wait_for: port=2379 timeout=60

  - name: Verify etcd cluster health
    shell: etcdctl cluster-health
    register: cmd_result

  - fail: msg='etcd cluster not healthy'
    when:
      - "'cluster is healthy' not in cmd_result.stdout"
