---

# Install OpenVPN
- hosts: openvpn
  become: true

  vars:
    openvpn_clients:
      - sample_vpn

  roles:
    - openvpn

  post_tasks:
    - name: Fetch client configs
      fetch: src=/etc/openvpn/clients/{{ item }}.zip dest={{ playbook_dir }}/../{{ item }}.zip flat=yes
      with_items: "{{ openvpn_clients }}"
