---

###################
# Install OpenVPN
###################

# Inventory: vpn_inventory


# Install OpenVPN
- hosts: openvpn
  become: true

  vars:
    openvpn_clients:
      - sample_vpn

  pre_tasks:
    - name: Wait until SSH is available
      local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH
      become: false

  roles:
    - openvpn

  post_tasks:
    - name: Fetch client configs
      fetch: src=/etc/openvpn/clients/{{ item }}.zip dest={{ playbook_dir }}/../{{ item }}.zip flat=yes
      with_items: "{{ openvpn_clients }}"
