---

etcd_client_port: 2379
etcd_peer_port: 2380
etcd_version: "v3.0.4"
etcd_release: "etcd-{{ etcd_version }}-linux-amd64"
etcd_download_filename: "{{ etcd_release }}.tar.gz"
etcd_download_url: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/{{ etcd_download_filename }}"
etcd_download_dir: /usr/local/src
etcd_data_dir: /var/lib/etcd
etcd_data_device: /dev/xvdh
