---

- name: Clear client zips
  file: path=/etc/openvpn/clients/{{ item }}.zip state=absent
  with_items: "{{clients}}"

- name: Clear client folders
  file: path=/etc/openvpn/clients/{{ item }} state=absent
  with_items: "{{clients}}"

- name: Generate client folders
  file: path=/etc/openvpn/clients/{{ item }} state=directory
  with_items: "{{clients}}"

- name: Generate client key
  command: openssl req -nodes -newkey rsa:4096 -keyout {{item}}.key -out {{item}}.csr -days 3650 -subj /CN=OpenVPN-Client-{{item}}/
    chdir=/etc/openvpn/keys
    creates={{item}}.key
  with_items: "{{clients}}"

- name: Sign client key
  command: openssl x509 -req -in {{item}}.csr -out {{item}}.crt -CA ca.crt -CAkey ca-key.pem -days 3650
    chdir=/etc/openvpn/keys
    creates={{item}}.crt
  with_items: "{{clients}}"

- name: Generate client config
  template: src=client.ovpn.j2 dest=/etc/openvpn/clients/{{item}}/{{item}}.ovpn owner=root group=root
  with_items: "{{clients}}"

- name: Move client crt
  command: mv -f /etc/openvpn/keys/{{item}}.crt /etc/openvpn/clients/{{item}}/
  with_items: "{{clients}}"

- name: Move client key
  command: mv /etc/openvpn/keys/{{item}}.key /etc/openvpn/clients/{{item}}/
  with_items: "{{clients}}"

- name: Copy ca.crt
  command: cp /etc/openvpn/keys/ca.crt /etc/openvpn/clients/{{item}}/
  with_items: "{{clients}}"

- name: Package client conf
  shell: zip -r {{item}}.zip {{item}}
  args:
    creates: "{{item}}.zip"
    chdir: /etc/openvpn/clients
  with_items: "{{clients}}"

# - name: Fetch client config
#   fetch: src=/etc/openvpn/clients/{{ item }}.zip dest={{ playbook_dir }}/{{item}}.zip flat=yes
#   with_items: "{{clients}}"
