- name: Create openvpn key directory
  file: path=/etc/openvpn/keys state=directory

- name: Generate CA key
  command: openssl req -nodes -newkey rsa:{{ openvpn_rsa_bits }} -keyout ca-key.pem -out ca-csr.pem -days 3650 -subj /CN=OpenVPN-CA/
    chdir=/etc/openvpn/keys
    creates=ca-key.pem

- name: Sign CA key
  command: openssl x509 -req -in ca-csr.pem -out ca.crt -CAcreateserial -signkey ca-key.pem -days 3650
    chdir=/etc/openvpn/keys
    creates=ca.crt

- name: Generate server key
  command: openssl req -nodes -newkey rsa:{{openvpn_rsa_bits}} -keyout server.key -out server.csr -days 3650 -subj /CN=OpenVPN/
    chdir=/etc/openvpn/keys
    creates=server.key

- name: Protect server key
  file: path=/etc/openvpn/keys/server.key mode=0400

- name: Generate CA serial
  shell: echo "01" > ca.srl
    chdir=/etc/openvpn/keys
    creates=ca.srl

- name: Copy openssl server extension config
  copy: src=openssl-server.ext dest=/etc/openvpn/keys owner=root group=root mode=0400

- name: Sign server key
  command: openssl x509 -req -in server.csr -out server.crt -CA ca.crt -CAkey ca-key.pem -days 3650 -extfile openssl-server.ext
    chdir=/etc/openvpn/keys
    creates=server.crt

- name: Generate tls-auth key
  command: openvpn --genkey --secret ta.key
    chdir=/etc/openvpn/keys
    creates=ta.key

# not a security issue, params aren't secret, just not generated by an attacker
# per http://security.stackexchange.com/questions/42415/openvpn-dhparam/42418#42418
- name: Copy pre-generated DH params
  copy: src=dh.pem dest=/etc/openvpn/keys owner=root group=root mode=0400
  when: openvpn_use_pregenerated_dh_params

# Alternatively, if you're concerned about logjam attacks
- name: Generate dh params
  command: openssl dhparam -out /etc/openvpn/keys/dh.pem {{ openvpn_rsa_bits }}
    chdir=/etc/openvpn/keys
    creates=dh.pem
  when: not openvpn_use_pregenerated_dh_params

- name: Create openvpn config file
  template: src=server.conf.j2 dest=/etc/openvpn/openvpn.conf owner=root group=root
  notify:
    - restart openvpn

- name: Copy openvpn logrotate config file
  copy: src=openvpn_logrotate.conf dest=/etc/logrotate.d/openvpn.conf owner=root group=root mode=0400
